### ISSUE TITLE
No DbContext was found in assembly using Net 7.0.400

### ISSUE THREAD

**Issue by DTeuchert** [khalidabuhakmeh/ef-core-multiple-providers#2]
I'm using .Net 7.0.400 and trying to add a new migration unsing the command:
```bash
C:\Users\me\source\github\ef-core-multiple-providers-main>dotnet ef migrations add InitialTest --project ./Migrations/BoxedSoftware.Sqlite -- --provider Sqlite
Build started...
Build succeeded.
No DbContext was found in assembly 'BoxedSoftware.Sqlite'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.
```

Do you have any solutions to fix this issue? The solution presented here to deal with multiple database providers makes a lot of sense to me.

**Comment by khalidabuhakmeh** [comment]
Apologies. I've fixed the issue and updated this repo. 

The command should be the following. You need to specify a `--startup-project` that includes the `Program.cs` which will bootstrap the `DbContext` instance.

```
 dotnet ef migrations add AnotherMigration --startup-project ./BoxedSoftware --project ./Migrations/BoxedSoftware.Sqlite -- --provider Sqlite 
```

🍻 Cheers :)
